version: "3.9" # optional since v1.27.0
services:
  web:
    build: .
    container_name: name
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  db:
    image: mysql:5.7
    container_name: my_database
    environment:
      MYSQL_ROOT_PASSWORD: atsawin
    volumes:
      - /var/lib/mysql
    networks:
      - api_network
  phpmyadmin:
    image: phpmyadmin  
    container_name: my_phpmyadmin
    links: 
      - db
    ports:
      - "8080:80"
    networks:
      - api_network
  redis:
    image: redis:alpine
    container_name: my_redis
    ports: 
      - "6379:6379"
    networks:
      - api_network
volumes:
  logvolume01: {}
networks:
  api_network: